name: actionlint

on:
  pull_request:
    paths:
      - .github/workflows/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        env:
          REF: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          set -euo pipefail
          git init .
          git remote add origin "https://github.com/${{ github.repository }}.git"
          git fetch --no-tags --prune --depth=1 origin "$REF"
          git checkout --force FETCH_HEAD
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
